no-resolv
server=1.1.1.1
address=/element.demo.local/10.89.0.100
address=/matrix.demo.local/10.89.0.100
address=/keycloak.demo.local/10.89.0.100
domain-needed
bogus-priv
listen-address=0.0.0.0
log-queries